formulas:
  - actionlint
  - ansible
  - argocd
  - aws-sam-cli
  - awscli
  - azure-cli
  - buf
  - bun
  - cocoapods
  - coreutils
  - ffmpeg
  - gh
  - git
  - gitleaks
  - helm
  - jq
  - k9s
  - kubernetes-cli
  - kustomize
  - minikube
  - mise
  - mongodb-database-tools
  - mongosh
  - mysql
  - packer
  - poppler
  - pup
  - redis
  - starship
  - uv
  - watch
  - xcodes
  - yamlfmt
  - yamllint
  - zsh
  - zsh-completions

casks:
  - 1password
  - appcleaner
  - aws-vpn-client
  - chatgpt
  - claude
  - claude-code
  - codex
  - deepl
  - discord
  - displaylink
  - docker-desktop
  - elgato-game-capture-hd
  - figma
  - firefox
  - font-fira-code-nerd-font
  - font-hack-nerd-font
  - font-ricty-diminished
  - gcloud-cli
  - google-japanese-ime
  - imageoptim
  - karabiner-elements
  - kiro-cli
  - loopback
  - ngrok
  - notion
  - notion-calendar
  - postman
  - raycast
  - slack
  - tradingview
  - tunnelbear
  - tunnelblick
  - visual-studio-code
  - visual-studio-code@insiders
